import { useState } from "react";

const SECTIONS = [
  { id: "start",     label: "Getting Started" },
  { id: "dashboard", label: "Dashboard" },
  { id: "backtest",  label: "Backtesting" },
  { id: "algos",     label: "Algorithms" },
  { id: "trading",   label: "Live Trading" },
  { id: "workflow",  label: "Recommended Workflow" },
  { id: "faq",       label: "FAQ" },
];

export function GuidePage() {
  const [active, setActive] = useState("start");

  return (
    <div className="page">
      <header className="page-header">
        <div>
          <h1 className="page-title">User Guide</h1>
          <p className="page-sub">How to use QuantEdge from zero to live trading</p>
        </div>
      </header>

      <div className="guide-layout">
        {/* TOC */}
        <nav className="guide-toc">
          {SECTIONS.map(s => (
            <button key={s.id}
              className={`guide-toc-item ${active === s.id ? "active" : ""}`}
              onClick={() => setActive(s.id)}
            >{s.label}</button>
          ))}
        </nav>

        {/* Content */}
        <div className="guide-content">

          {active === "start" && (
            <Section title="Getting Started">
              <P>QuantEdge is an algorithmic trading platform. It lets you:</P>
              <Ul items={[
                "View live candlestick chart data for stocks and crypto",
                "Backtest algorithmic trading strategies against years of historical data",
                "Configure strategy parameters and understand how each works",
                "Execute strategy signals in real time on a paper (simulated) trading account",
                "Monitor your positions, orders, and account P&L live",
              ]} />
              <Callout type="info" title="Paper Trading">
                This platform is configured for <strong>paper trading by default</strong> — you use simulated money, not real funds. No real capital is at risk. Perfect for learning and testing strategies safely.
              </Callout>
              <H3>Prerequisites</H3>
              <P>You need a free Alpaca account with paper trading credentials. Set them in <code>backend/.env</code>:</P>
              <Code>{`ALPACA_API_KEY=your_key
ALPACA_SECRET_KEY=your_secret
ALPACA_BASE_URL=https://paper-api.alpaca.markets
ALPACA_DATA_FEED=iex`}</Code>
              <P>Then start the platform:</P>
              <Code>{`./start.sh`}</Code>
              <P>The frontend opens at <code>http://localhost:3000</code> and the API at <code>http://localhost:8000</code>.</P>
            </Section>
          )}

          {active === "dashboard" && (
            <Section title="Dashboard">
              <P>The Dashboard is your real-time market overview. It shows a candlestick price chart for any stock or crypto, with signals overlaid from all active strategies.</P>
              <H3>Selecting a Symbol</H3>
              <P>Use the dropdown in the top-right to switch between symbols. The list includes major stocks (AAPL, TSLA, NVDA) and crypto (BTC/USD, ETH/USD). You can type any valid Alpaca symbol in the backtest and trading pages.</P>
              <H3>Timeframe Buttons</H3>
              <P>Buttons across the top right control the time resolution:</P>
              <Table
                headers={["Button", "Candle Size", "Typical Range"]}
                rows={[
                  ["1H", "1-hour candles", "Last 30 days"],
                  ["4H", "4-hour candles", "Last 90 days"],
                  ["1D", "Daily candles", "Last year"],
                  ["3Y", "Daily candles", "3 years"],
                  ["5Y", "Daily candles", "5 years"],
                  ["MAX", "Daily candles", "Since 2016 (Alpaca IEX max)"],
                  ["1W", "Weekly candles", "Since 2016"],
                ]}
              />
              <Callout type="info" title="IEX Data Feed">
                The free Alpaca tier uses the IEX data feed, which has a 15-minute delay and intraday data limited to 30 days. Daily and weekly data goes back to 2016.
              </Callout>
              <H3>Signal Feed</H3>
              <P>The panel on the right shows the latest signal generated by each strategy for the current symbol. Green = BUY, Red = SELL. This updates each time you change symbol.</P>
              <H3>Metric Cards</H3>
              <P>The four cards below the header show: last price with % change, period high, period low, and most recent candle volume.</P>
            </Section>
          )}

          {active === "backtest" && (
            <Section title="Backtesting">
              <P>Backtesting lets you simulate a strategy against historical data to see how it would have performed — before risking any capital.</P>
              <H3>Single Strategy Mode</H3>
              <Ol items={[
                'Select "Single Strategy" tab',
                "Enter a symbol (e.g. AAPL, NVDA, BTC/USD)",
                "Choose a strategy from the dropdown",
                "Set the date range — the platform defaults to 2016–today for maximum history",
                "Set initial capital (default $10,000)",
                "Set commission if your broker charges per trade (Alpaca paper trading is free, so leave at 0)",
                'Click "Run Backtest"',
              ]} />
              <Callout type="tip" title="Strategy Parameters">
                The strategy uses the parameters you configured in the <strong>Algorithms</strong> tab. Change them there and re-run the backtest to see the impact.
              </Callout>
              <H3>Reading the Results</H3>
              <Table
                headers={["Metric", "What it means", "Good value"]}
                rows={[
                  ["Total Return", "Overall % gain/loss over the period", "Positive"],
                  ["Sharpe Ratio", "Return per unit of risk (volatility)", "> 1.0"],
                  ["Max Drawdown", "Worst peak-to-trough loss you'd have experienced", "Less negative is better"],
                  ["Win Rate", "% of trades that closed at a profit", "> 50%"],
                  ["Profit Factor", "Gross profits ÷ gross losses", "> 1.5"],
                  ["Avg Holding Days", "Average time a position was held", "Depends on strategy"],
                ]}
              />
              <H3>Compare All Mode</H3>
              <P>Switch to "Compare All" to run every strategy on the same symbol and date range simultaneously. Results are sorted by Sharpe Ratio. This is a quick way to find which strategy fits the asset best.</P>
              <H3>Portfolio Backtest Mode</H3>
              <P>Run one strategy across multiple symbols at once. Each symbol gets an equal allocation of capital. The combined equity curve shows how the portfolio would have grown. Use this to test diversification.</P>
              <Callout type="warning" title="Backtesting Limitations">
                Backtests simulate a simplified model: long-only, one position at a time per symbol, market orders with no partial fills. Real trading has slippage, liquidity constraints, and taxes. A good backtest shows potential — not guaranteed returns.
              </Callout>
            </Section>
          )}

          {active === "algos" && (
            <Section title="Algorithms">
              <P>The Algorithms page lets you explore and configure each strategy before deploying it.</P>
              <H3>Three Tabs Per Strategy</H3>
              <Ul items={[
                "Overview — plain-English explanation, analogy, step-by-step logic, and a real example",
                "Parameters — interactive sliders to adjust every setting, with descriptions of what each does",
                "Tuning Tips — specific advice on how to optimise for different market conditions",
              ]} />
              <H3>Configuring Parameters</H3>
              <P>Use the sliders or number inputs in the Parameters tab to change a strategy's settings. Your changes are <strong>saved automatically</strong> and will be used the next time you:</P>
              <Ul items={[
                "Run a backtest for that strategy",
                "Execute a strategy signal from the Live Trading page",
              ]} />
              <P>Click <strong>↺ Reset defaults</strong> to restore the original values.</P>
              <H3>Strategy Quick Reference</H3>
              <Table
                headers={["Strategy", "Market Type", "Key Idea"]}
                rows={[
                  ["MA Crossover", "Trending", "Buy when fast MA crosses above slow MA"],
                  ["RSI", "Range-bound", "Buy when oversold (< 30), sell when overbought (> 70)"],
                  ["Bollinger Bands", "Volatile / mean-reverting", "Buy when price bounces off lower band"],
                  ["MACD", "Momentum trend", "Buy when MACD line crosses above signal line"],
                  ["Grid Trading", "Sideways / oscillating", "Buy at price dips, sell at fixed intervals above entry"],
                ]}
              />
            </Section>
          )}

          {active === "trading" && (
            <Section title="Live Trading">
              <P>The Live Trading page connects to your Alpaca paper account to execute orders and monitor your portfolio in real time.</P>
              <Callout type="warning" title="Paper Trading Only">
                All orders execute against a simulated paper account. No real money is involved. The platform does not support live trading without additional configuration and careful testing.
              </Callout>
              <H3>Account Strip</H3>
              <P>The strip at the top of the page shows your key account metrics, updated every 30 seconds:</P>
              <Ul items={[
                "Portfolio Value — total equity (cash + open position value)",
                "Cash — uninvested cash balance",
                "Buying Power — how much you can spend right now",
                "Unrealized P&L — gain/loss on currently open positions",
                "Day P&L — today's equity change vs yesterday's close",
                "Session Return — return since you opened this browser session",
              ]} />
              <H3>Algo Execution Tab</H3>
              <P>This is the core trading workflow:</P>
              <Ol items={[
                "Select a symbol and strategy",
                "Set the quantity (number of shares or units)",
                'Click "▶ Execute Signal"',
                "The platform fetches the latest signal for that strategy",
                "If the signal is BUY and you have no open position, a market buy order is placed",
                "If the signal is SELL and you have an open position, a market sell order is placed",
                "The execution is logged to the Strategy Execution Log table below",
              ]} />
              <Callout type="tip" title="Strategy Parameters">
                The strategy uses the parameters from the <strong>Algorithms</strong> tab. Tune them there to change signal sensitivity before executing.
              </Callout>
              <H3>Portfolio Equity Curve</H3>
              <P>Once the platform has observed at least two portfolio value snapshots (30 seconds apart), it shows a live equity curve of your session performance.</P>
              <H3>Manual Orders Tab</H3>
              <P>For placing ad-hoc market orders without a strategy signal. Select BUY or SELL, enter a symbol and quantity, and submit. Useful for manually closing positions or testing order flow.</P>
              <H3>Positions & Order Tables</H3>
              <Ul items={[
                "Open Positions — all current holdings with avg entry price, current price, and unrealized P&L. Click 'Close' to flatten any position.",
                "Open Orders — pending orders not yet filled. Click 'Cancel' to cancel.",
                "Recent Fills — last 30 completed orders with fill price and timestamp.",
              ]} />
            </Section>
          )}

          {active === "workflow" && (
            <Section title="Recommended Workflow">
              <P>Here's the end-to-end workflow for deploying a strategy responsibly:</P>
              <Ol items={[
                "Start on the Dashboard. Pick a symbol and look at price action across different timeframes. Is it trending, ranging, or volatile? This tells you which strategy type to consider.",
                "Go to Algorithms. Read the Overview and Tuning Tips for strategies that match the market conditions you observed. Adjust the parameters for your hypothesis.",
                "Go to Backtest. Run the strategy on the symbol with a long date range (at least 2-3 years). Check: Is the Sharpe Ratio > 1? Is Max Drawdown acceptable? Does the equity curve look smooth or erratic?",
                "Run Compare All on the same symbol. Does your chosen strategy outperform others on a risk-adjusted basis?",
                "Try Portfolio Backtest with 3-5 related symbols. Does the strategy hold up across different assets?",
                "If results look good, go to Live Trading. Start with a small quantity (1 share). Execute the strategy signal and observe how the order fills.",
                "Monitor the position from the Positions table. Watch the Unrealized P&L over time.",
                "When your strategy generates a SELL signal, execute again to close the position.",
                "Review the Recent Fills table to assess your actual execution vs the backtest simulation.",
              ]} />
              <Callout type="warning" title="Important Reminder">
                Past backtest performance does not guarantee future results. Always use paper trading to validate a strategy before considering live capital. Start with small positions and scale slowly.
              </Callout>
            </Section>
          )}

          {active === "faq" && (
            <Section title="FAQ">
              <FAQ q="Why does the chart only show data back to 2016?" a="The Alpaca IEX free data feed begins in 2016. This is the maximum available history without a paid data subscription. You can change ALPACA_DATA_FEED=sip in your .env if you upgrade to a paid Alpaca plan." />
              <FAQ q="Why is the signal 'HOLD' or null?" a="A HOLD signal means the strategy's conditions for a BUY or SELL haven't been met. For example, RSI must cross above 30 to trigger a BUY — if RSI is at 45 and moving sideways, no actionable signal exists. Try a longer lookback or different parameters." />
              <FAQ q="The 'Execute Signal' button says SELL but I have no position. What happens?" a="The platform checks for an open position before executing a SELL. If none exists, it will warn you and not place the order. This prevents shorting accidentally on a paper account." />
              <FAQ q="Why does the backtest show 0 trades?" a="This usually means the strategy didn't generate any signals in the date range. Try a longer date range, or adjust the parameters (e.g. widen the RSI thresholds) to make the strategy more sensitive." />
              <FAQ q="How do I add a new symbol?" a='Any symbol tradeable on Alpaca works. Just type it directly into the Symbol field on the Backtest or Trading page. For crypto, use the format BTC/USD. Check the full list at alpaca.markets.' />
              <FAQ q="What does 'IEX feed' mean?" a="IEX is an alternative US stock exchange. Alpaca free accounts get data from IEX, which covers most major US stocks with a 15-minute delay. Intraday data (1H, 4H) is limited to the last 30 days on this feed." />
              <FAQ q="How do I know if my parameters are being used?" a='Parameters set in the Algorithms tab are saved automatically. You can verify them by checking the "Strategy Params" section in backtest results, or looking at the signal confidence level when you execute.' />
              <FAQ q="Can I run this against a live trading account?" a="The code supports live trading but this requires changing ALPACA_BASE_URL to https://api.alpaca.markets in your .env and thoroughly testing the strategy first. Do not do this without understanding the risks." />
            </Section>
          )}

        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className="guide-section"><h2 className="guide-h2">{title}</h2>{children}</div>;
}
function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="guide-h3">{children}</h3>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="guide-p">{children}</p>;
}
function Ul({ items }: { items: string[] }) {
  return <ul className="guide-ul">{items.map((item, i) => <li key={i}>{item}</li>)}</ul>;
}
function Ol({ items }: { items: string[] }) {
  return <ol className="guide-ol">{items.map((item, i) => <li key={i}>{item}</li>)}</ol>;
}
function Code({ children }: { children: string }) {
  return <pre className="guide-code"><code>{children}</code></pre>;
}
function Callout({ type, title, children }: { type: "info"|"tip"|"warning"; title: string; children: React.ReactNode }) {
  const colors = { info: "var(--blue)", tip: "var(--green)", warning: "var(--orange)" };
  const icons  = { info: "ℹ", tip: "✓", warning: "⚠" };
  return (
    <div className="guide-callout" style={{ "--callout-color": colors[type] } as any}>
      <div className="guide-callout-title"><span>{icons[type]}</span>{title}</div>
      <div className="guide-callout-body">{children}</div>
    </div>
  );
}
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) {
  return (
    <div className="table-wrap guide-table-wrap">
      <table className="data-table">
        <thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead>
        <tbody>{rows.map((r, i) => <tr key={i}>{r.map((c, j) => <td key={j}>{c}</td>)}</tr>)}</tbody>
      </table>
    </div>
  );
}
function FAQ({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="faq-item">
      <button className="faq-q" onClick={() => setOpen(o => !o)}>
        <span>{open ? "▾" : "▸"}</span>{q}
      </button>
      {open && <p className="faq-a">{a}</p>}
    </div>
  );
}
